config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'pages#home'

  get 'about', to:'pages#about'
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence:true ,length: {minimum: 3, maximum: 50 }
  validates :description, presence:true,length: {minimum: 3}
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :name, :email, :password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_action :set_article, only: [:edit, :update, :show, :destroy]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:success]="Article was successfully created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger]= "Article deleted"
    redirect_to articles_path
  end

  def edit
  end

  def update

  if @article.update(article_params)
      flash[:success]="Article was successfully updated !!"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def home

end

def about

end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def correct_user?(user)
     current_user == user
  end

end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>
<div class='row'>
<div class='col-xs-12'>
  <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="form-group">
    <div class="control-label col-sm-2">
      <%= f.label :title %>
    </div>
    <div class="col-sm-8">
     <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
     <div class="control-label col-sm-2">
      <%= f.label :description %>
    </div>
    <div class="col-sm-8">
      <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of article" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary btn-lg' %>
    </div>
  </div>
  <% end %>
    <div class="col-xs-4 col-xs-offset-4">
       [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 align = "center">Edit existing Article</h1>

<%= render 'form'%>

app/views/articles/index.html.erb
<h1 align = "center"> Listing all articles </h1>

<% @articles.each do |article|%>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article)%>
        </div>
         <div class="article-body">
          <%= truncate(article.description, length:80)%>
        </div>
        <div class="article-actions">
        <%if correct_user?(article.user)%>
         <%= link_to "Edit this Article", edit_article_path(article), class:"btn btn-xs btn-primary" %>
         <%= link_to "Delete this Article", article_path(article),
                                            method: :delete, data: {confirm: "Are u sure?"},
                                            class:"btn btn-xs btn-danger" %>
        <%end%>
        </div>
      </div>
    </div>
  </div>`
<%end%>

app/views/articles/new.html.erb
<h1 align = "center">Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%=@article.title%></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <h4 class="center description"><strong>Description:</strong></h4>
  <hr>
     <%= simple_format(@article.description) %>
<div class="article-actions">
  <% if correct_user?(@article.user)%>
    <%= link_to "Edit this Article", edit_article_path, class:"btn btn-xs btn-primary" %>
    <%= link_to "Delete this Article", article_path(@article),
                                      method: :delete, data: {confirm: "Are u sure?"},
                                      class:"btn btn-xs btn-danger" %>
  <%end%>
  <%= link_to "View all Articles", articles_path, class:"btn btn-xs btn-success" %>
</div>

app/views/layouts/_footer.html.erb
<div class:"container">
  <footer class: "footer">
    <small>
      Copyright &copy; <a href="https://prepsocial.herokuapp.com">Prepsocial</a> by Abhinav Garg
    </small>
    <nav>
      <ul>
       <li><%= link_to "About", about_path %> </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
<% flash.each do |name, msg|%>
    <div class='alert alert-<%="#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
    </div>
  </div>
</div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha blog", root_path, class:'navbar-brand', id:"logo" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Articles", articles_path %></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Article <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New", new_article_path %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <%if user_signed_in?%>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
         </ul>
      <%else%>
        <li><%= link_to "Sign Up", new_user_registration_path%></li>
        <li><%= link_to "Sign In", user_session_path %></li>
      <%end%>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= favicon_link_tag 'favicon.png' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation'%>
  <%= render 'layouts/messages'%>
  <div class= "container">
  <%= yield %>
  <%= render 'layouts/footer'%>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>This is about page for alpha blog</h1>


<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Alpha Blog</h1>
  <p><%= link_to "Sign up Now", new_user_registration_path, id:"Submit", class: "btn btn-large btn-xlarge" %></p>
</div>

app/views/shared/_errors.html.erb
<% if  obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel-danger">
        <div class= "panel-heading">
          <h2 class="panel-title">
            <%= pluralize( obj.errors.count,"error") %>
              prohibited the article from getting created:</h2>
            <div class = "panel-body">
                <ul>
                  <%  obj.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
                </ul>
            </div>
         </div>
      </div>
     </div>
   </div>

<% end %>